### ISSUE TITLE
Create a protobuf for a new privileged API on SPIRE Agent

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire-api-sdk#4]
Pursuant to https://github.com/spiffe/spire/issues/2246, we need a new API for privileged platform components to interact with SPIRE Agent for the purpose of delegated SVID management.

There are many possible shapes here, and given the use cases I've seen before I can think of at least a few. That said, there is one immediate need that is clear. I suggest we start with just one or two RPCs, the minimum to meet the use case at hand, knowing that we will likely add more RPCs in the future as additional integration work arises.

**Comment by mauriciovasquezbernal** [comment]
The shape of this API could be very similar to the [Spiffe workload API ](https://github.com/spiffe/spiffe/blob/011b3d35ba238ddfaf6060bc9d30f5e0a7ad9fb9/standards/workloadapi.proto#L5). The major difference is that the request should include information about the workload to fetch the SVID for. 

I think we should allow the privileged client to specify the workload by using the PID or the container/pod ID. 

- **PID**: This will be supported by all workload attestation plugins (unix/docker/k8s) and this is already [passed](https://github.com/spiffe/spire-plugin-sdk/blob/165234a661367528af02ec5df895650709e709ad/proto/spire/plugin/agent/workloadattestor/v1/workloadattestor.proto#L17) from SPIRE to the plugin. 
- **container/pod ID**: This option should only be supported by attestation plugins aware of containers (docker and k8s). 

The reason I'd like to also be able to get the SVID by specifying the container/pod ID is that it's **very** difficult to get the PID of a K8s pod/container. The PID is not exposed in the K8s API, hence we need to talk to the container runtime to get it. Unfortunately there is not a common interface to query the different runtimes and even knowing its configuration (like UDS where it listens) is difficult because it's not exposed anywhere. 

Said that, I imagine the request message could look like:

```
message X509SVIDRequest {
    // Credentials of the workload to attestate.
    oneof credentials {
        // Pid of the process to attest
        int32 pid = 1;
        // Uid of the container to attest
        string container_uid = 2;
        // Uid of the Kubernetes pod to attest
        string pod_uid = 3;
    }
}
```

> I suggest we start with just one or two RPCs

I'm particularly interested in the `FetchX509SVID` one. It should be enough for our Cilium-SPIFFE use case.

**Comment by mauriciovasquezbernal** [comment]
> It would be useful to know a little more about exactly what kind of information you do have access to, and where it comes from. 

Sure, let me try to summarize it. We plan to use the SVIDs in two different places: cilium-agent and cilium-proxy. 

In cilium-agent we are only interested on the SPIFFE ID (to use it when calculating the [endpoint identity](https://docs.cilium.io/en/v1.9/concepts/terminology/#identity)). In this agent we have a "slim" version of a K8s [Pod](https://pkg.go.dev/github.com/cilium/cilium@v1.9.6/pkg/k8s/slim/k8s/api/core/v1#Pod) object. We'd be able to get more fields of the full K8s [pod](https://pkg.go.dev/golang.org/x/build/kubernetes/api#Pod) object if needed. 

In the cilium-proxy (based on Envoy) we want to use the X509SVID to upgrade connections to mTLS. In this proxy we have the identity of the pod (endpoint) initiating the connection. 

Te high level steps of the architecture I have thought are:

0. The user creates the registration entries for the pods. 
1. A pod is created
2. cilium-agent gets the SVID (SPIFFE ID + X509) for this pod using this privileged API and it calculates the identity for this pod with its SPIFFE ID
3. cilium-agent sends the X509 certificates of this identity to cilium-proxy
4. cilium-proxy adds this to a cache of identities -> X509 certificates
5. The pod initiates a connection
6. cilium-proxy gets the identity of the pod initiating the connection by using some eBPF maps 
7. cilium-proxy gets the X509 certificates to use in this connection from the cache of point 4
8. cilium-proxy upgrades the connection

According to these steps, it'd be cilium-agent that uses this privileged API to fetch the SVIDs of the pods and then it passes that information to cilium-proxy. 

> On a previous call, I think eBPF-based packet marking was mentioned, I'm not sure what all is possible to inject there, or if there are other mechanisms/channels through which you are learning about the source of the traffic.

I was wrong with eBPF-based packet marking. It's used but for other purpose. cilium-proxy is able to determine the identity of the pod initiating the connection by using some eBPF maps created by Cilium like the [ipcache](https://docs.cilium.io/en/v1.8/cmdref/cilium_bpf_ipcache_list/). 

> That last point shows that, if we take the selector route, it will be useful to have a conversation about how entries are created and by whom.

I think the user should be the one creating the registration entries in this case. They are the ones with the knowledge about how to define the security policies, I can't image how we could create the registration entries in another (automatic?) way.

**Comment by evan2645** [comment]
> In cilium-agent we are only interested on the SPIFFE ID (to use it when calculating the endpoint identity). In this agent we have a "slim" version of a K8s Pod object. We'd be able to get more fields of the full K8s pod object if needed.

Got it. So in cilium-agent ... you will want to loop through these pod objects I assume? And then for each one, ask SPIRE for SVIDs for it?

> In the cilium-proxy (based on Envoy) we want to use the X509SVID to upgrade connections to mTLS. In this proxy we have the identity of the pod (endpoint) initiating the connection.

With this point and the one above ... It sounds like the granularity of identity is pod-level, correct? SPIRE has the ability to look deeper than pod, and can differentiate between different containers and/or processes running inside the pod. So if the Cilium notion of identity is pod-centric, I think that says something about the shape of the registration entries for this particular integration - they should address a pod and not something more specific than that.

Is this sounding right?

> I think the user should be the one creating the registration entries in this case. They are the ones with the knowledge about how to define the security policies, I can't image how we could create the registration entries in another (automatic?) way.

Many people create registrations automatically using the admission controller that ships with SPIRE ([k8s-workload-registrar](https://github.com/spiffe/spire/tree/main/support/k8s/k8s-workload-registrar)). This controller requires use of a particular set of node and workload attestors (`k8s_psat` and `k8s`, respectively), and creates registration entries automatically using the selectors those attestors produce.

> So if the Cilium notion of identity is pod-centric, I think that says something about the shape of the registration entries for this particular integration - they should address a pod and not something more specific than that.

If the assumption about pod-centric identity is correct, this is an important detail due to the way that SPIRE handles selectors. Cilium can call SPIRE and provide a set of selectors that describe the pod it wants an identity for ... however, entries are matched to callers iff the caller has _all_ of the selectors specified by the registration entry (it may also have more i.e. the registration entry selectors can be a subset of the caller's selectors).

This means if a user is managing their own registration entries, and they decide to scope them down tighter than pod level ... for example, by container image ID or by binary SHA ... Cilium will not be in a position to provide these selectors over the privileged API, and thus would not be able to obtain the SVID for the pod of interest (and even Cilium could retrieve them, they would be used in ways that would likely surprise the user).

So, I think we need to be opinionated about the selectors that this integration uses, and the particular shape of the registration entries that we define? Sorry, I know this is a little off-topic for this issue, I just want to make sure that we're gonna build the thing that solves your problem

**Comment by evan2645** [comment]
Ok yes ... this is all sounding very good! I have some further thoughts on the selector values to use (perhaps a combination of the selectors generated by k8s attestor and custom cillium selectors?) but that can be discussed later.

So in terms of the protobuf message you pasted, what do you think of this?

```proto
message X509SVIDRequest {
    // A reference to the workload for which you need an SVID.
    oneof reference {
        // PID of the workload you're interested in
        int32 pid = 1;

        // Selectors describing the workload you're interested in
        repeated string selector = 2;
    }
}
```

At any rate, I think this will be best further discussed over PR. Mind sending one with the full proto and we can review there? Also paging @azdagron in case he has any thoughts on api shape here

**Comment by azdagron** [comment]
The `selectors` field there will operate more or less as a replacement for selectors we'd normally obtain via workload attestation? i.e. we'd match entries whose selectors represented a subset of those provided in the request?

**Comment by mauriciovasquezbernal** [comment]
> ```protobuf
>         repeated string selector = 2;
> ```

I have the same question as @azdagron, are these selectors the same as the generated by the attestation plugins?

**Comment by evan2645** [comment]
Short answer: yes I think we take the selectors and match against entries the same way we do during workload attestation

Long answer: I have been thinking about all this, from a conceptual standpoint... and what I have arrived at is this:

If a privileged caller is providing selectors, then we are effectively delegating workload attestation to it. Instead of exercising workload attestation, wherein selectors describing the workload are discovered, we have a caller who is saying "I know the selectors for the workload I represent, and here they are". So in some ways, the caller of this RPC is acting as a special kind of workload attestor. In the end, we trust this caller to faithfully apply or issue the SVID (similar to the way that we trust a workload attestor to faithfully provide selectors).

With that understood, we can see that this caller can provide any selectors they want, without restriction. This means they can provide selectors that are the same as that produced by workload attestor plugins, or selectors that are different and/or dedicated to the integration, or both of those things. They have different effects.

For a concrete example. Suppose cilium-agent provides the following two selectors as part of its request:
* `k8s:pod-uid:1234abc`
* `cilium:pod-uid:1234abc`

This arrangement allows the user to register a pod using the k8s selector, and in this case cilium can get an SVID for the pod, _and so can workloads inside the pod_ because they will also match the k8s selectors when attested. This can be desirable when you have application-layer logic that needs keys or SVIDs (e.g. JWT-SVID). Conversely, if the user registers a pod using the Cilium-specific selector, then they can prevent the workload itself from retrieving the SVID but still ensure that Cilium receives it. This can be desirable in high security environments where you don't want the workload receiving private keys.

@mauriciovasquezbernal please find below to links for reference. SPIRE Agent internals have a cache with subscription mechanism. You can subscribe using a set of selectors, where you will be sent any registration entries that have a subset of the selectors you provided. This is how workload attestation works - we get a bunch of selectors from the attestors, the full set of selectors describes a single caller or workload, and we subscribe that caller to the cache using the full set.
https://github.com/spiffe/spire/blob/main/pkg/agent/manager/cache/cache.go#L202
https://github.com/spiffe/spire/blob/main/pkg/agent/manager/manager.go#L40-L42

Hopefully this all makes sense 😅

**Comment by azdagron** [comment]
That jives with me! Thanks for taking the time to spell that out, @evan2645. It does limit the registration entries that cilium can reach to those that _only_ contain selectors that cilium knows how to produce instead of any arbitrary registration entry that might otherwise be applied to the workload had it been directly attested, but that limitation seems reasonable?

**Comment by mauriciovasquezbernal** [comment]
Your idea @evan2645 is different than the one I was thinking about as it requires the user to create the registration entries with the same selectors that cilium agent uses for retrieving them. This case doesn't use the k8s workload attestor at all but it's the privileged client (cilium-agent) who specifies the selectors to use. 

Let me try to explain one use case that I think we can't support by using this approach. Let's suppose a user wants to create a policy that allows all pods running an `ubuntu` image to communicate with all pods running a `debian` image. 
First of all the user would define two registration entries:

```
$ spire-server entry create \
    -spiffeID spiffe://example.org/myubuntupods \
    -selector k8s:pod-image:ubuntu:latest

$ spire-server entry create \
    -spiffeID spiffe://example.org/mydebianpods \
    -selector k8s:pod-image:debian:latest
```

Then the user specifies a cilium network policy like:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "image-based"
spec:
  endpointSelector:
    matchLabels:
      spiffe://example.org/myubuntupods: ""
  egress:
  - toEndpoints:
    - matchLabels:
        spiffe://example.org/mydebainpods: ""
```

And that's all. 

I think using the k8s attestator plugin is the key point what would allow us to support use cases as the above, as it's the one with all the logic to generate the different selectors. The k8s workload attestor would allow the cilium agent to ask "who is this pod?" without relying in any specific registration entries. It'd also allow the user to create them without taking into consideration how cilium performs the request. 

I'm happy to know what you think of this use case and if you see any possibility to support it with your idea.

**Comment by mauriciovasquezbernal** [comment]
Let me also share one possible idea for the implementation/API. (Please be kind, I know changing interfaces around is not nice but I don't have other ideas :D ).

I think we can make the request message of this API generic:

```
// Credentials of the workload to attestate.
message Credentials {
   string type = 1;
   string value = 2;
}

message X509SVIDRequest {
   Credentials credentials = 1;
}
```
`type` is workload credential type: `pid`, `pod_uid` or `container_uid`. The core of SPIRE is not aware of them. Only workload attestator plugins care about them, i.e, more credentials types can be supported by new workload attestation plugins without any change to the core of SPIRE.

We extend/change the [AttestRequest](https://github.com/spiffe/spire/blob/8971d3d6b3003235deb73ed42e04fdd72dfb55e6/proto/spire/plugin/agent/workloadattestor/v0/workloadattestor.proto#L12) message to include such credentials. Then each attestation plugin should check if it supports the type of credential, if it does it performs the attestation and returns the selectors, otherwise it returns no selectors.

For instance, `pid` type is supported by the unix, docker and k8s attestation plugins, `container_uid` by docker and k8s and `pod_uid` only by the k8s one. This should be extensible and new types could be supported by other attestation plugins in the future if needed. 

If we are worried about performance of using `strings` (between SPIRE and the attestation plugins) we can make an exception for pid, the `AttestRequest` message could be something like:

```
/** Represents the workload to attest.*/
message AttestRequest {
    /** Workload PID */
    int32 pid = 1;
   /** workload credentials */
   optional Credentials credentials = 2;
}
```

Also, if we want to be less intrusive we could even define a new rpc for the `WorkloadAttestor` service without touching the current `Attest` one.

```
message AttestByCredentialsRequest {
   Credentials credentials = 1;
}
rpc AttestByCredentials(AttestByCredentialsRequest) returns (AttestByCredentialsResponse);
```

Does it make sense at all?

**Comment by evan2645** [comment]
> Let me try to explain one use case that I think we can't support by using this approach. Let's suppose a user wants to create a policy that allows all pods running an ubuntu image to communicate with all pods running a debian image.
First of all the user would define two registration entries:

I think that what I was proposing will work for this use case, as cilium-agent can send the `k8s:pod-image` selector as part of its API call, and it should be in a position to generate this (and all other k8s selectors) because it has access to the pod spec? I'm pretty sure it would work exactly as you described in this example.

The one caveat is that we could not support non-k8s selectors (as SPIRE gets these from places other than pod spec and cilium-agent probably won't have a way to discover them).

> I think using the k8s attestator plugin is the key point what would allow us to support use cases as the above, as it's the one with all the logic to generate the different selectors.

Most of the logic inside k8s workload attestor is around finding the right pod spec in the kubelet. The logic to parse the pod spec and generate selectors from it (once we find the right one) is relatively simple.

I do think that it is a little weird to couple the cilium integration to the k8s selectors in this way, and if the k8s workload attestor ever grew support for additional selectors, cilium would have to also explicitly grow support for them. That said, we have kind of similar coupling right now with the k8s-workload-registrar and we haven't had many problems there in practice.

> We extend/change the AttestRequest message to include such credentials. Then each attestation plugin should check if it supports the type of credential, if it does it performs the attestation and returns the selectors, otherwise it returns no selectors.
>
> For instance, pid type is supported by the unix, docker and k8s attestation plugins, container_uid by docker and k8s and pod_uid only by the k8s one. This should be extensible and new types could be supported by other attestation plugins in the future if needed.

Hmm ok, I will think about this one. It will be very disruptive, and a pretty fundamental shift on the workload attestation subsystem. I would envision this kind of thing like a "workload reference" (rather than credentials which suggests use of some secret value), where PID is one way to reference a workload. Shaking this up will probably take some time to think through it, discuss the changes, get everyone comfortable etc... lots of compatibility questions and related implications would likely make this route less desirable than one that works well with the current model and interfaces

Since we use PID as workload reference already, a PID-based lookup against the privileged API would be straightforward, and would also solve the caveat described above (allowing users to set any k8s or non-k8s selectors they want, and cilium can avoid having to know about these selectors). But I understand that PID may be difficult for cilium to get.

**Comment by evan2645** [comment]
> Most of the logic inside k8s workload attestor is around finding the right pod spec in the kubelet. The logic to parse the pod spec and generate selectors from it (once we find the right one) is relatively simple.

🤔 maybe one possibility here is we can export this logic to you via go package and share it ... pod spec goes in, selectors come out. That way staying up-to-date should be low touch and things will be more or less consistent.

I have been thinking more too about the workload reference stuff. If the reference is pod uid, then the only workload attestor that can make use of this is k8s workload attestor ... so with this reference, we'd still be limited to k8s only selectors ... another problem is that the k8s workload attestor knows how to find the specific container in the pod that is calling ... and this would be lost with pod uid reference. So we would need specific logic inside the k8s attestor to skip this part, and we'd have one set of selectors we get with regular workload attestation, and a subset of those only when referenced by pod uid.

**Comment by mauriciovasquezbernal** [comment]
Sorry for the delay, I was away last week.

> I think that what I was proposing will work for this use case, as cilium-agent can send the k8s:pod-image selector as part of its API call

Oh yes, I missed it from your idea, it can work. 

> Since we use PID as workload reference already, a PID-based lookup against the privileged API would be straightforward, and would also solve the caveat described above (allowing users to set any k8s or non-k8s selectors they want, and cilium can avoid having to know about these selectors). But I understand that PID may be difficult for cilium to get.

Unfortunately getting the Pod's PID from the PodSpec is a PITA, otherwise we could go for the PID-based one. 

> :thinking: maybe one possibility here is we can export this logic to you via go package and share it ... pod spec goes in, selectors come out. That way staying up-to-date should be low touch and things will be more or less consistent.

It's a good idea, just a dependency update should be enough in case there are changes in SPIRE. 

> another problem is that the k8s workload attestor knows how to find the specific container in the pod that is calling ... and this would be lost with pod uid reference

We could have both, attesting by container UID and pod UID, it's up to the caller to use the right one.

I'm fine with going with the selectors idea if you think this solution is generic enough and other users could benefit from it. 

Said that, we should remove the PID from the request message. The PID should be part of a different rpc as the logic is a bit different in both cases, i.e, when the PID is provided the SPIRE workload attestation plugins will be used, when the selectors are provided they won't be used. 

What about something like? 

```
message X509SVIDRequest {
    // Selectors describing the workload you're interested in
    repeated string selector = 1;
}
```

**Comment by evan2645** [comment]
> Unfortunately getting the Pod's PID from the PodSpec is a PITA, otherwise we could go for the PID-based one.

Yes ... I know how hard it can be 😆 we have spent a lot of time in SPIRE not only figuring this out, but also how to do it securely... In fact, the more I think about it, the more I feel that PID is a bad idea for external caller.

> It's a good idea, just a dependency update should be enough in case there are changes in SPIRE.
> ...
> I'm fine with going with the selectors idea if you think this solution is generic enough and other users could benefit from it.

Ok, awesome. If this works for you, I think it is the best balance... with emphasis on making sure it works for you :)

> Said that, we should remove the PID from the request message.

Yea.. I don't think we should implement that right now. I worry about security-sensitive races there. SPIRE implements some non-trivial code to prevent this kind of thing, and to do PID safely, the caller of the privileged API would need to implement this safety code as well.

> What about something like?

Yes I think this makes sense. @azdagron may have some thoughts about RPC and message naming, but from a shape and behavior standpoint, this is looking good! I think we are ready to take a PR here with the new proto ... once it is merged, we can bump the SPIRE dependency and begin work on the implementation. I am happy to carve out some issues for that work if it is a help to you.

**Comment by azdagron** [comment]
Happy to discuss the RPC and message names in the PR. Might be easier then, seeing the whole thing together instead of in bits and pieces :)

**Comment by mauriciovasquezbernal** [comment]
> with emphasis on making sure it works for you :)

I'll try to prototype this quickly to see if I hit any unexpected issue. 

> I think we are ready to take a PR here with the new proto 

Will do. 

> I am happy to carve out some issues for that work if it is a help to you

Yes, I think those will help me to organize this work, thanks!
